language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules
script:
  - npm run build
# before_deploy:
#   - cd out/
#   - touch .nojekyll

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: out
#   repo: IronKinoko/e-hentai-view
#   target_branch: gh-pages
#   on:
#     branch: master
