name: Publish Docker image
on:
  release:
    types: [ created ]
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: true
          tags: ironkinoko/e-hentai-view:${{ github.event.release.tag_name }}
